@istest
Private class testBatchSearchRequest
{
    Static testMethod void testBatchSearchRequest()
    {
        ID i='003Q000000OWEP5';
       //  BatchSearchRequest b =new BatchSearchRequest(i,true,'701Q00000006iKV');
         BatchSearchRequest.BatchSearchRequest(i,true,'701Q00000006iKV');
         
       //  testBatchSearchRequest.BatchSearchRequest(i,true,'701Q00000006iKV');
        //BatchSearchRequest b =new BatchSearchRequest('003Q000000OWEP5',true,'701Q00000006iKV');
    }
}